name: On Pull Request Opened

on:
  pull_request:
    branches: [feature/discount]

jobs:
  lint:
    name: Lint Debug Variant
    uses: ./github/workflows/job_lint_debug.yml

  test:
    name: Test Debug Variant
    uses: ./github/workflows/job_test_debug.yml

